version: '3'
services:
  router:
    build:
      context: .
      dockerfile: Dockerfile-local
    image: quay.io/team-helium/router:local
    container_name: helium_router
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - "./data:/var/data"
    depends_on:
      - prometheus
  prometheus:
      image: prom/prometheus
      container_name: helium_prometheus
      network_mode: host
      volumes:
          - "./prometheus.yml:/etc/prometheus/prometheus.yml"