FROM heliumsystems/builder-erlang:2

WORKDIR /opt/router

# FIXME: do NOT merge with this _checkouts hack!
# See https://github.com/msantos/inert/pull/8
# which adds #include <stdint.h> to inert/c_src/inert_drv.c
ADD _checkouts/ _checkouts/

ADD rebar3 rebar3
ADD rebar.config rebar.config
ADD rebar.lock rebar.lock
ADD config/grpc_client_gen.config config/grpc_client_gen.config
ADD config/grpc_server_gen.config config/grpc_server_gen.config
RUN ./rebar3 get-deps
RUN ./rebar3 compile

ADD Makefile Makefile
ADD c_src/ c_src/
ADD include/ include/
ADD src/ src/
ADD scripts/ scripts/
RUN make

ADD config/ config/
ADD priv/ priv/
RUN make rel

ADD test/ test/
# This is only to fetch tests dependencies
RUN ./rebar3 as test compile

CMD ["make", "run"]
