version: '3'
services:
  router:
    build:
      context: .
      dockerfile: Dockerfile-local
    image: quay.io/team-helium/router:local
    container_name: helium_router
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - "/var/data:/var/data"
    depends_on:
      - prometheus
  prometheus:
      image: prom/prometheus
      container_name: helium_prometheus
      network_mode: host
      volumes:
          - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: helium_node_exporter
    command:
      - '--path.rootfs=/host'
      - "--collector.disable-defaults"
      - "--collector.filesystem"
      - "--collector.netstat"
      - "--collector.meminfo"
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
