{
 "title": "Router",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "server", "label": "Server", "query": "router" }
  ]
 },
 "panels": [
  {
   "title": "Durations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Offer -> Packet -> Downlink",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(router_device_packet_trip_duration_sum{server=\"$server\", type=\"join\"}[5m])/rate(router_device_packet_trip_duration_count{server=\"$server\", type=\"join\"}[5m])",
       "legendFormat": "Join downlink={{downlink}}"
      },
      {
       "expr": "rate(router_device_packet_trip_duration_sum{server=\"$server\", type=\"packet\"}[5m])/rate(router_device_packet_trip_duration_count{server=\"$server\", type=\"packet\"}[5m])",
       "legendFormat": "Packet  downlink={{downlink}}"
      }
     ]
    },
    {
     "title": "Travel Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(rate(router_device_packet_trip_duration_sum{server=\"$server\", type=\"join\", downlink=\"true\"}[5m])/rate(router_device_packet_trip_duration_count{server=\"$server\", type=\"join\", downlink=\"true\"}[5m])) * -1",
       "legendFormat": "join_total"
      },
      {
       "expr": "(rate(router_device_routing_packet_duration_sum{server=\"$server\", status=\"accepted\", type=\"join\", downlink=\"true\"}[5m])/rate(router_device_routing_packet_duration_count{server=\"$server\", status=\"accepted\", type=\"join\", downlink=\"true\"}[5m]))*-1",
       "legendFormat": "join_local"
      },
      {
       "expr": "(rate(router_device_packet_trip_duration_sum{server=\"$server\", type=\"packet\", downlink=\"true\"}[5m])/rate(router_device_packet_trip_duration_count{server=\"$server\", type=\"packet\", downlink=\"true\"}[5m])) * -1",
       "legendFormat": "packet_total"
      },
      {
       "expr": "(rate(router_device_routing_packet_duration_sum{server=\"$server\", status=\"accepted\", type=\"packet\", downlink=\"true\"}[5m])/rate(router_device_routing_packet_duration_count{server=\"$server\", status=\"accepted\", type=\"packet\", downlink=\"true\"}[5m]))*-1",
       "legendFormat": "packet_local"
      }
     ]
    },
    {
     "title": "Offer Durations",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(router_device_routing_offer_duration_sum{server=\"$server\", status=\"accepted\"}[5m])/rate(router_device_routing_offer_duration_count{server=\"$server\", status=\"accepted\"}[5m])",
       "legendFormat": "{{type}}   accepted"
      },
      {
       "expr": "rate(router_device_routing_offer_duration_sum{server=\"$server\", status=\"rejected\"}[5m])/rate(router_device_routing_offer_duration_count{server=\"$server\", status=\"rejected\"}[5m])",
       "legendFormat": "{{type}}   rejected  {{reason}}"
      }
     ]
    },
    {
     "title": "Packet Durations",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(router_device_routing_packet_duration_sum{server=\"$server\", status=\"accepted\"}[5m])/rate(router_device_routing_packet_duration_count{server=\"$server\", status=\"accepted\"}[5m])",
       "legendFormat": "{{type}}   accepted downlink={{downlink}}"
      },
      {
       "expr": "rate(router_device_routing_packet_duration_sum{server=\"$server\", status=\"rejected\"}[5m])/rate(router_device_routing_packet_duration_count{server=\"$server\", status=\"rejected\"}[5m])",
       "legendFormat": "{{type}}   rejected -  {{reason}}"
      },
      {}
     ]
    },
    {
     "title": "Hold Time  Percentiles",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, rate(router_device_packet_hold_time_duration_bucket{server=\"$server\", type=\"packet\"}[5m]))",
       "legendFormat": "1"
      },
      {
       "expr": "histogram_quantile(0.99, rate(router_device_packet_hold_time_duration_bucket{server=\"$server\", type=\"packet\"}[5m]))",
       "legendFormat": "0.99"
      },
      {
       "expr": "histogram_quantile(0.98, rate(router_device_packet_hold_time_duration_bucket{server=\"$server\", type=\"packet\"}[5m]))",
       "legendFormat": "0.98"
      },
      {
       "expr": "histogram_quantile(0.95, rate(router_device_packet_hold_time_duration_bucket{server=\"$server\", type=\"packet\"}[5m]))",
       "legendFormat": "0.95"
      },
      {
       "expr": "histogram_quantile(0.90, rate(router_device_packet_hold_time_duration_bucket{server=\"$server\", type=\"packet\"}[5m]))",
       "legendFormat": "0.90"
      },
      {
       "expr": "histogram_quantile(0.50, rate(router_device_packet_hold_time_duration_bucket{server=\"$server\", type=\"packet\"}[5m]))",
       "legendFormat": "0.50"
      },
      {
       "expr": "histogram_quantile(0.10, rate(router_device_packet_hold_time_duration_bucket{server=\"$server\", type=\"packet\"}[5m]))",
       "legendFormat": "0.10"
      },
      {
       "expr": "histogram_quantile(0.05, rate(router_device_packet_hold_time_duration_bucket{server=\"$server\", type=\"packet\"}[5m]))",
       "legendFormat": "0.05"
      },
      {
       "expr": "histogram_quantile(0.02, rate(router_device_packet_hold_time_duration_bucket{server=\"$server\", type=\"packet\"}[5m]))",
       "legendFormat": "0.02"
      },
      {
       "expr": "histogram_quantile(0.01, rate(router_device_packet_hold_time_duration_bucket{server=\"$server\", type=\"packet\"}[5m]))",
       "legendFormat": "0.01"
      }
     ]
    },
    {
     "title": "Hold Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(router_device_packet_hold_time_duration_sum{server=\"$server\"}[5m])/rate(router_device_packet_hold_time_duration_count{server=\"$server\"}[5m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Functions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "rate(router_function_duration_sum{server=\"$server\"}[5m])/rate(router_function_duration_count{server=\"$server\"}[5m])",
       "legendFormat": "{{function}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Offers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Join Offer Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(router_device_routing_offer_duration_count{server=\"$server\", type=\"join\", status=\"accepted\"}[5m]))",
       "legendFormat": "Accepted"
      },
      {
       "expr": "sum(rate(router_device_routing_offer_duration_count{server=\"$server\", type=\"join\", status=\"rejected\"}[5m]))",
       "legendFormat": "Rejected"
      }
     ]
    },
    {
     "title": "Packet Offer Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(router_device_routing_offer_duration_count{server=\"$server\", type=\"packet\", status=\"accepted\"}[5m]))",
       "legendFormat": "Accepted"
      },
      {
       "expr": "sum(rate(router_device_routing_offer_duration_count{server=\"$server\", type=\"packet\", status=\"rejected\"}[5m]))",
       "legendFormat": "Rejected"
      }
     ]
    },
    {
     "title": "Offer Rejected Reasons",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(router_device_routing_offer_duration_count{server=\"$server\", status=\"rejected\"}[5m])",
       "legendFormat": "{{type}} - {{reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Join Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(router_device_routing_packet_duration_count{server=\"$server\", type=\"join\", status=\"accepted\"}[5m]))",
       "legendFormat": "Accepted"
      },
      {
       "expr": "sum(rate(router_device_routing_packet_duration_count{server=\"$server\", type=\"join\", status=\"rejected\"}[5m]))",
       "legendFormat": "Rejected"
      }
     ]
    },
    {
     "title": "Packet  Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(router_device_routing_packet_duration_count{server=\"$server\", type=\"packet\", status=\"accepted\"}[5m]))",
       "legendFormat": "Accepted"
      },
      {
       "expr": "sum(rate(router_device_routing_packet_duration_count{server=\"$server\", type=\"packet\", status=\"rejected\"}[5m]))",
       "legendFormat": "Rejected"
      },
      {
       "expr": "sum(rate(router_device_routing_packet_duration_count{server=\"$server\", type=\"discovery_packet\", status=\"accepted\"}[5m]))",
       "legendFormat": "Discovery accepted"
      }
     ]
    },
    {
     "title": "Downlinks Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(router_device_downlink_packet{server=\"$server\"}[5m])",
       "legendFormat": "{{type}} = {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Blockchain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last block",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "router_blockchain_blocks{server=\"$server\"}"
      }
     ]
    },
    {
     "title": "DC Balance",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "router_dc_balance{server=\"$server\"}",
       "legendFormat": "Balance"
      }
     ]
    },
    {
     "title": "XOR Filter",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "router_xor_filter{server=\"$server\"}",
       "legendFormat": "Previous TXN Cost"
      }
     ]
    },
    {
     "title": "State Channels",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "router_state_channel_overspent_count{server=\"$server\"}",
       "legendFormat": "Overspent"
      },
      {
       "expr": "router_state_channel_active_count{server=\"$server\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "router_state_channel_opened_count{server=\"$server\"}-router_state_channel_active_count{server=\"$server\"}",
       "legendFormat": "Passive"
      }
     ]
    },
    {
     "title": "Active State Channels Actors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(router_state_channel_active_actors{server=\"$server\"})",
       "legendFormat": "Actors"
      }
     ]
    },
    {
     "title": "Active State Channels Balance",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "router_state_channel_active_balance{server=\"$server\"}",
       "legendFormat": "Balance"
      }
     ]
    },
    {
     "title": "Close Conflicts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "router_state_channel_close_conflicts{server=\"$server\"}",
       "legendFormat": "Close Conflicts"
      }
     ]
    },
    {
     "title": "State Channel Close Submit Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
     "targets": [
      {
       "expr": "router_sc_close_submit_count{server=\"$server\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "State Channel Close Submit RATE over 12H",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
     "targets": [
      {
       "expr": "rate(router_sc_close_submit_count{server=\"$server\"}[12h])",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Decoders",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg decoder time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(router_decoder_decoded_duration_sum{server=\"$server\", status=\"ok\"}[5m]) / rate(router_decoder_decoded_duration_count{server=\"$server\", status=\"ok\"}[5m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "OK / Error Rate",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(router_decoder_decoded_duration_count{server=\"$server\", status=\"ok\"}[5m])",
       "legendFormat": "{{type}} ok"
      },
      {
       "expr": "rate(router_decoder_decoded_duration_count{server=\"$server\", status=\"error\"}[5m])",
       "legendFormat": "{{type}} error"
      }
     ]
    }
   ]
  },
  {
   "title": "APIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Success %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(router_console_api_duration_count{server=\"$server\", status=\"ok\"}[5m])) / (sum(rate(router_console_api_duration_count{server=\"$server\", status=\"error\"}[5m])) + sum(rate(router_console_api_duration_count{server=\"$server\", status=\"ok\"}[5m]))) * 100",
       "legendFormat": "API Success %"
      }
     ]
    },
    {
     "title": "Console Webscoket",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "router_ws_state{server=\"$server\"}",
       "legendFormat": "WS Online"
      }
     ]
    },
    {
     "title": "Console API Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(router_console_api_duration_sum{server=\"$server\", status=\"ok\"}[5m])/rate(router_console_api_duration_count{server=\"$server\", status=\"ok\"}[5m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Console API OK Rates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(router_console_api_duration_count{server=\"$server\", status=\"ok\"}[5m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Console API Error Rates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(router_console_api_duration_count{server=\"$server\", status=\"error\"}[5m])",
       "legendFormat": "{{type}} = {{status}}"
      },
      {
       "expr": "rate(router_console_api_duration_count{server=\"$server\", status=\"not_found\"}[5m])",
       "legendFormat": "{{type}} = {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "VM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "GRPC connection count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "router_grpc_connection_count{server=\"$server\"}",
       "legendFormat": "grpc connections"
      }
     ]
    },
    {
     "title": "Process Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "erlang_vm_process_count{server=\"$server\"}",
       "legendFormat": "Process Count"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(router_vm_cpu{server=\"$server\"})/count(router_vm_cpu{server=\"$server\"})",
       "legendFormat": "All"
      }
     ]
    },
    {
     "title": "Process Queue",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "router_vm_process_queue{server=\"$server\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Single ETS memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "router_vm_ets_memory{server=\"$server\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(erlang_vm_memory_processes_bytes_total{server=\"$server\"})",
       "legendFormat": "processes"
      },
      {
       "expr": "erlang_vm_memory_system_bytes_total{server=\"$server\"}",
       "legendFormat": "{{usage}}"
      },
      {
       "expr": "sum(erlang_vm_memory_system_bytes_total{server=\"$server\"}) + sum(erlang_vm_memory_processes_bytes_total{server=\"$server\"})",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_load1{server=\"$server\"}",
       "legendFormat": "1m load average"
      },
      {
       "expr": "node_load5{server=\"$server\"}",
       "legendFormat": "5m load average"
      },
      {
       "expr": "node_load15{server=\"$server\"}",
       "legendFormat": "15m load average"
      },
      {
       "expr": "count(node_cpu_seconds_total{server=\"$server\", mode=\"idle\"})",
       "legendFormat": "logical cores"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(((1 - rate(node_cpu_seconds_total{mode=\"idle\", server=\"$server\"}[1m]))/ ignoring(cpu) group_left  count without (cpu)( node_cpu_seconds_total{mode=\"idle\", server=\"$server\"})))",
       "legendFormat": "{{cpu}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 -(  avg(node_memory_MemAvailable_bytes{server=\"$server\"})/  avg(node_memory_MemTotal_bytes{server=\"$server\"})* 100)"
      }
     ]
    },
    {
     "title": "Memory Available %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node_memory_MemAvailable_bytes{server=\"$server\"} / node_memory_MemTotal_bytes{server=\"$server\"}",
       "legendFormat": "Memory Available %"
      }
     ]
    },
    {
     "title": "Filesystem",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(max by (device) (  node_filesystem_size_bytes{server=\"$server\", fstype!=\"\"}-node_filesystem_avail_bytes{server=\"$server\", fstype!=\"\"}))",
       "legendFormat": "used"
      },
      {
       "expr": "sum(max by (device) (  node_filesystem_avail_bytes{server=\"$server\", fstype!=\"\"}))",
       "legendFormat": "available"
      }
     ]
    },
    {
     "title": "Memory Available %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes{server=\"$server\"}-node_memory_MemFree_bytes{server=\"$server\"}-node_memory_Buffers_bytes{server=\"$server\"}-node_memory_Cached_bytes{server=\"$server\"})",
       "legendFormat": "memory used"
      },
      {
       "expr": "node_memory_Buffers_bytes{server=\"$server\"}",
       "legendFormat": "memory buffers"
      },
      {
       "expr": "node_memory_Cached_bytes{server=\"$server\"}",
       "legendFormat": "memory cached"
      },
      {
       "expr": "node_memory_MemFree_bytes{server=\"$server\"}",
       "legendFormat": "memory free"
      }
     ]
    }
   ]
  }
 ]
}