name: BUILD_AND_PUSH_IMG

on:
  push:
    tags: '*'

jobs:
  quay:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          repository: team-helium/router
          tag_with_ref: true
          push: true